name: Docker Image CI

on:
  push:
    branches-ignore:
      - 'main'

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build -t poet .

      - name: Run Docker Container
        run: docker run -t -d --name test-container poet

      - name: Run unit tests
        run: docker exec test-container python3 -m unittest tests
